Allow changing the "color scheme" in the preview pane.
mrabiciu/UIViewPreviewProvider pull request #1
Opened 2019-11-14 14:38 UTC by pykaso

2019-11-14 20:45 UTC, mrabiciu requested changes
I think this makes sense, but we can generalize it a bit more to allow showing light and dark mode side by side automatically.

What do you think?

2019-11-14 20:45 UTC, mrabiciu commented on UIViewPreviewProvider.swift
> +    static var colorScheme: ColorScheme { get }
This means we'd need to create two different `UIViewPreviewProvider` in order to preview both light mode and dark mode.

Lets make this an array instead:
```swift
static var colorSchemes: [ColorScheme] { get }
```

which we can default to:
```swift
public static var colorSchemes: [ColorScheme] {
    [.light, .dark]
}
```

2019-11-14 20:45 UTC, mrabiciu commented on UIViewPreviewProvider.swift
>      }
Then down here we can iterate over all the color schemes and make a preview for each of them
```swift
    public static var previews: some View {
        
        let identifiablePreviews = uiPreviews.map {
            IdentifiableBox($0)
        }
        
        let identifieableSchemes = colorSchemes.map {
            IdentifiableBox($0)
        }
        
        return ForEach(identifiablePreviews) { preview in
            ForEach(identifieableSchemes) { scheme in
                swiftUIView(from: preview.item)
                    .environment(\.colorScheme, scheme.item)
            }
        }
    }
```

2019-11-15 09:10 UTC, pykaso commented
> I think this makes sense, but we can generalize it a bit more to allow showing light and dark mode side by side automatically.
> 
> What do you think?

I like this idea. Nice job.

2019-11-15 17:59 UTC, mrabiciu approved these changes

2019-11-15 17:59 UTC, merged

2019-11-15 17:59 UTC, mrabiciu commented
Thanks for contributing!